
sky:
  datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        host: localhost
        port: 3306
        database: sky_take_out
        username: root
        password: 1234
  alioss:
   endpoint: oss-cn-beijing.aliyuncs.com
   access-key-id:  ${ALIBABA_ACCESS_KEY}
   access-key-secret: ${ALIBABA_SECRET_KEY}
   bucket-name: zuiyunlan
  redis:
    host: localhost
    port: 6379
    password: 1234
    database: 10
  wechat:
    appid: wx3df3947e7129608c
    secret: 554380c77f8d223eccc7ea1046c0ec43